from django.urls import path
from accounting.api import views

urlpatterns = [
    path('purchase-create/', views.PurchaseCreateAPIView.as_view()),
    path('purchase-retrieve-update-delete/<int:id>/', views.PurchaseRetrieveUpdateDestroyAPIView.as_view()),
    path('purchase-list/', views.PurchaseListAPIView.as_view()),
    path('purchaselist-list/', views.PurchaseListListAPIView.as_view()),
    path('purchaselist-retrieve/<int:id>/', views.PurchaseListRetrieveAPIView.as_view()),
    path('purchaselist-update/<int:id>/', views.PurchaseListUpdateAPIView.as_view()),
    path('purchaselist-delete/<int:id>/', views.PurchaseListDestroyAPIView.as_view()),
    path('bulk-purchase/', views.BulkPurchaseAPIView.as_view()),
    path('stock-list/', views.StockListAPIView.as_view()),
    path('addtostock/', views.AddToStockAPIView.as_view()),
    path('stock-retrieve-update-delete/<int:id>/', views.StockRetrieveUpdateDestroyAPIView.as_view()),
    path('sale-list/', views.SaleListAPIView.as_view()),
    path('short-sale-list/', views.ShortSaleListAPIView.as_view()),
    path('salelist-list/', views.SaleListListAPIView.as_view()),
    path('salelist-retrieve/<int:id>/', views.SaleListRetrieveAPIView.as_view()),
    path('salelist-update/<int:id>/', views.SaleListUpdateAPIView.as_view()),
    path('salelist-delete/<int:id>/', views.SaleListDestroyAPIView.as_view()),
    path('sale-create/', views.SaleCreateAPIView.as_view()),
    path('sale-retrieve-update-delete/<int:id>/', views.SaleRetrieveUpdateDestroyAPIView.as_view()),
    path('bulk-sale/', views.BulkSaleAPIView.as_view()),
    path('payment-list/', views.PaymentListAPIView.as_view()),
    path('payment-create/', views.PaymentCreateAPIView.as_view()),
    path('payment-retrieve-update-delete/<int:id>/', views.PaymentRetrieveUpdateDestroyAPIView.as_view()),
    path('productaction-list/<int:id>/', views.ProductActionListAPIView.as_view()),
    path('customeraction-list/<int:id>/', views.CustomerActionListAPIView.as_view()),
    path('customeraction-retrieve/<int:id>/', views.CustomerActionListRetrieveAPIView.as_view()),
    path('returnback-list/', views.ReturnBackListAPIView.as_view()),
    path('returnback-create/', views.ReturnBackCreateAPIView.as_view()),
    path('returnback-retrieve-update-delete/<int:id>/', views.ReturnBackRetrieveUpdateDestroyAPIView.as_view()),
    path('expense-list/', views.ExpenseListAPIView.as_view()),
    path('expense-create/', views.ExpenseCreateAPIView.as_view()),
    path('expense-retrieve-update-delete/<int:id>/', views.ExpenseRetrieveUpdateDestroyAPIView.as_view()),
    path('invoice-list/<int:id>/', views.InvoiceListAPIView.as_view()),
    path('dashboard/<int:seller_id>/<str:month>/<int:year>/', views.DashboardAPIView.as_view()),
    path('saledynamics/<int:seller_id>/<str:filter_data>/<int:brand_id>/', views.SaleDynamicsAPIView.as_view()),
    path('mostindebtedcustomers/', views.MostInDebtedCustomerAPIView.as_view()),
    path('stockoutproducts-list/', views.StockOutProductsListAPIView.as_view()),
    path('supplierpayment-list/', views.SupplierPaymentListAPIView.as_view()),
    path('supplierpayment-create/', views.SupplierPaymentCreateAPIView.as_view()),
    path('supplierpayment-retrieve-update-delete/<int:id>/', views.SupplierPaymentRetrieveUpdateDestroyAPIView.as_view())
]