from django.urls import path
from accounting.api import views

urlpatterns = [
    path('purchase-create/', views.PurchaseCreateAPIView.as_view()),
    path('purchase-retrieve-update-delete/<int:id>/', views.PurchaseRetrieveUpdateDestroyAPIView.as_view()),
    path('purchase-list/', views.PurchaseListAPIView.as_view()),
    path('stock-list/', views.StockListAPIView.as_view()),
    path('addtostock/', views.AddToStockAPIView.as_view()),
    path('sale-list/', views.SaleListAPIView.as_view()),
    path('sale-create/', views.SaleCreateAPIView.as_view()),
    path('sale-retrieve-update-delete/<int:id>/', views.SaleRetrieveUpdateDestroyAPIView.as_view()),
    path('bulk-sale/', views.BulkSaleAPIView.as_view()),
    path('payment-list/', views.PaymentListAPIView.as_view()),
    path('payment-create/', views.PaymentCreateAPIView.as_view()),
    path('payment-retrieve-update-delete/<int:id>/', views.PaymentRetrieveUpdateDestroyAPIView.as_view()),
    path('productaction-list/<int:id>/', views.ProductActionListAPIView.as_view()),
    path('customeraction-list/<int:id>/', views.CustomerActionListAPIView.as_view()),
    path('returnback-list/', views.ReturnBackListAPIView.as_view()),
    path('returnback-create/', views.ReturnBackCreateAPIView.as_view()),
    path('returnback-retrieve-update-delete/<int:id>/', views.PurchaseRetrieveUpdateDestroyAPIView.as_view()),
    path('expense-list/', views.ExpenseListAPIView.as_view()),
    path('expense-create/', views.ExpenseCreateAPIView.as_view()),
    path('expense-retrieve-update-delete/<int:id>/', views.PurchaseRetrieveUpdateDestroyAPIView.as_view()),
    path('invoice-list/<int:id>/', views.InvoiceListAPIView.as_view()),
    path('dashboard/<int:seller_id>/', views.DashbordAPIView.as_view()),
    path('saledynamics/<int:seller_id>/<str:filter_data>/', views.SaleDynamicsAPIView.as_view()),
    path('mostindebtedcustomers/', views.MostInDebtedCustomerAPIView.as_view()),
    path('stockoutproducts-list/', views.StockOutProductsListAPIView.as_view()),
]